model = "gpt-5-codex"
model_reasoning_effort = "high"
approval_policy = "never"

[projects."/Users/billy.lee/workspace/webserver"]
trust_level = "trusted"

[projects."/Users/billy.lee/workspace/cyber-orchestration"]
trust_level = "trusted"

[projects."/Users/billy.lee/workspace/cyber-lifecycle"]
trust_level = "trusted"

[features]
web_search_request = true

[notice]
hide_full_access_warning = true
