model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
approval_policy = "never"
personality = "friendly"
web_search = "live"
sandbox_mode = "danger-full-access"

[projects."/Users/billy.lee/workspace/webserver"]
trust_level = "trusted"

[projects."/Users/billy.lee/workspace/cyber-orchestration"]
trust_level = "trusted"

[projects."/Users/billy.lee/workspace/cyber-lifecycle"]
trust_level = "trusted"

[features]
steer = true
multi_agent = true

[mcp_servers.glean_default]
url = "https://coalition-be.glean.com/mcp/default"

[mcp_servers.datadog]
url = "https://mcp.datadoghq.com/api/unstable/mcp-server/mcp"

